#  __      __       .__
# /  \    /  \ ____ |  |   ____  ____   _____   ___________
# \   \/\/   // __ \|  | _/ ___\/  _ \ /     \_/ __ \_  __ \
#  \        /\  ___/|  |_\  \__(  <_> )  Y Y  \  ___/|  | \/
#   \__/\  /  \___  >____/\___  >____/|__|_|  /\___  >__|
#        \/       \/          \/            \/     \/
# The prefix that should be used in the plugin
Prefix: "&7[&eWelcomer&7]"

NoPermissionMessage: "&cYou do not have permission to use this command."

# Message of the Day (MOTD)
MOTD:
  # Whether the MOTD feature is enabled or not
  Enabled: true

  # The messages to be sent to the player
  Messages:
    - "&7-=-=-=-=-=-=-=-=-=-"
    - "&aWelcome to &2MyServer"
    - "&aOnline players: &2%online%/20"
    - "&aStore: &2mystore.net"
    - "&7-=-=-=-=-=-=-=-=-=-"

# Join/Quit messages
Join:
  # Whether the join/quit messages feature should be enabled
  Enabled: true

  # The message for a player joining the server for the first time
  FirstJoinMessage: "&aWelcome &2%player% &afor joining &2MyServer &afor the first time ever."

  # The message for a player joining the server
  JoinMessage: "&aWelcome back to &2myserver.net &2%player%!"

Quit:
  # Whether the quit messages feature should be enabled
  Enabled: true

  # The message for a player quitting the server
  QuitMessage: "&aGoodbye &2%player% &a, see you next time!"

# Title welcome message
Title:
  # Whether the Title welcome feature should be enabled
  Enabled: true

  # The title of the title message
  Title: "&aWelcome to &2&nMyserver"

  # The subtitle of the title message
  Subtitle: "&a%player%"

  # Time for the title to fade in (in ticks)
  FadeIn: 20

  # Time for the title to stay on screen (in ticks)
  Stay: 60

  # Time for the title to fade out (in ticks)
  FadeOut: 20

# ActionBar welcome message
ActionBar:
  # Whether the ActionBar welcome feature should be enabled
  Enabled: false

  # The message sent to the player through the action bar
  Message: "&aWelcome to &2MyServer &a%player%"

# Sound played when a player joins the server
Sound:
  # Whether the sound feature should be enabled
  Enabled: true

  # The sound to be played
  Sound: ENTITY_PLAYER_LEVELUP

  # Volume of the sound
  Volume: 1.0

  # Pitch of the sound
  Pitch: 1.0

# GUI configuration
GUI:
  # Whether the GUI feature should be enabled
  Enabled: true
