#  __      __       .__
# /  \    /  \ ____ |  |   ____  ____   _____   ___________
# \   \/\/   // __ \|  | _/ ___\/  _ \ /     \_/ __ \_  __ \
#  \        /\  ___/|  |_\  \__(  <_> )  Y Y  \  ___/|  | \/
#   \__/\  /  \___  >____/\___  >____/|__|_|  /\___  >__|
#        \/       \/          \/            \/     \/

# The prefix that should be used in the plugin
Prefix: "&7[&eWelcomer&7]"

# Permission node that the player must have to reload the configuration (/welcomer reload)
PermissionReload: "welcomer.reload"

# Permission node that the player must have to configure the plugin from in-game through the gui (/welcomer menu)
PermissionMenu: "welcomer.menu"

NoPermissionMessage: "&cYou do not have permission to use this command."

# Message of the day
MOTD:

  # Whether the MOTD feature is enabled or not
  Enabled: true

  # The message that should be sent to the player when they join the server
  Message:
    - "&7-=-=-=-=-=-=-=-=-=-"
    - "&aWelcome to &2MyServer"
    - "&aOnline players: &2%online%/20"
    - "&aStore: &2mystore.net"
    - "&7-=-=-=-=-=-=-=-=-=-"

# Join/Quit messages
JoinWelcome:

  # Whether the join/quit messages feature should be enabled
  Enabled: true

  # The message that should be sent when a player joins the server for the first time
  First-Join-Message: "&aWelcome &2%plater% &afor joining &2MyServer &afor the first time ever."

  # The message that should be sent when a player joins the server
  Join-Message: "&aWelcome back to &2myserver.net &2%player%!"

QuitWelcome:

  # Whether the quit messages feature should be enabled
  Enabled: true

  # The message that should be sent when a player quits the server
  Quit-Message: "&aGoodbye &2%player% &a, see you next time!"

# This welcomes players with a title message.
TitleWelcome:

  # Whether the Title welcome feature should be enabled
  Enabled: true

  # The title of the title message
  Title: "&aWelcome to &2&nMyserver"

  # The subtitle of the title message
  SubTitle: "&a%player%"

  # The time that the title should fade in for in ticks. Default: 20
  FadeIn: 20

  # The time that the title should stay on the plauers screen in ticks. Default: 60
  Stay: 60

  # The time that the title should fade out for in ticks. Default: 20
  FadeOut: 20

ActionBarWelcome:

  # Whether the ActionBar welcome feature should be enabled
  Enabled: false

  # The message that should be sent to the player through the action bar.
  Message: "&aWelcome to &2MyServer &a%player%"

  # The sound that should be played when the action bar message is sent
  # TODO - Move sound into its independent section
  Sound:

    # Whether the sound should be enabled
    Enabled: true

    # The sound that should be played | https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    Sound: ENTITY_EXPERIENCE_ORB_PICKUP

    # The volume of the sound
    Volume: 1.0

    # The pitch of the sound
    Pitch: 1.0

# The GUI that the player will see when they run /welcomer menu
GUI:

  # Whether the GUI feature should be enabled
  Enabled: true