name: Welcomer
author: Gregzee
description: Welcomer aims to add different ways of welcoming your players on your server from quit and join messages to MOTDs, titles, sounds, actionbars and much more with extensive configuration and much more.
main: me.gregzee.welcomer.Welcomer
version: '2.0.0'
api-version: '1.13'
load: POSTWORLD

depend:
  - PlaceholderAPI

commands:
  welcomer:
    description: The main command for the plugin
    usage: /welcomer <reload|menu>

permissions:
  welcomer.commands.reload:
    description: Allows the player to reload the config
    default: op
  welcomer.commands.menu:
    description: Allows the player to open the GUI
    default: op