name: Welcomer
version: '${project.version}'
main: me.gregzee.welcomer.Welcomer
api-version: '1.16'
authors: [Gregzee]
website: https://gregzee.me
commands:
  welcomer:
    usage: /<command>
    aliases:
      - welc
    description: Main command of the Welcomer plugin.