name: Welcomer
author: Gregzee
description: your description here
main: me.gregzee.welcomer.Welcomer
version: '1.0.0'
api-version: '1.13'
load: POSTWORLD

depend:
  - PlaceholderAPI

commands:
  welcomer:
    description: The main command for the plugin
    usage: /welcomer <reload|menu>

permissions:
  welcomer.commands.reload:
    description: Allows the player to reload the config
    default: op
  welcomer.commands.menu:
    description: Allows the player to open the GUI
    default: op